export const REPLACE_FEATURE = 'REPLACE_FEATURE'
export const DESELECT_FEATURES = 'DESELECT_FEATURES'
export const SELECTED_FEATURE = 'SELECTED_FEATURE'
export const SET_FEATURES_FROM_ARRAY = 'SET_FEATURES_FROM_ARRAY'
export const SET_ALL_FEATURES = 'SET_FEATURES'

export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'

export const SET_GROUPS = 'SET_GROUPS'
